# Setup
title:               The Jershon Lopez Fan Club
tagline:             'A place to talk about myself'
description:         'A personal website to protect my domain.'
url:                 https://jylopez.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jershon Lopez
  url:               https://jylopez.github.io/
  email:             jershonlopez@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
